### ISSUE TITLE
Missing example file

### ISSUE THREAD

**Issue by GitHubBlues** [dalmo1991/superflexPy#1]
Dear superflexPy developers, 
The package you developed looks really interesting! 
I tried to run the examples, but am missing a function. 

With my local superflexPy installation ...

> ImportError: cannot import name 'FastReservoir' from 'superflexpy.implementation.elements.hbv' (C:\Users\Usuario\AppData\Roaming\Python\Python37\site-packages\superflexpy\implementation\elements\hbv.py)

... and also when using the Notebook

> ImportError: cannot import name 'FastReservoir' from 'superflexpy.implementation.elements.hbv' (/srv/conda/envs/notebook/lib/python3.7/site-packages/superflexpy/implementation/elements/hbv.py)

Thanks.

**Comment by dalmo1991** [comment]
Dear @GitHubBlues ,
Thank you for trying SuperflexPy and for opening the issue.
With version 1.2.0, the `FastReservoir` has been renamed to `PowerReservoir`. This is what generates your error. 
We forgot to apply the change in the code inside the `examples/` folder. Now we have solved the issue with commit e755ade643bfcc0324fc638033e1f1b794f17a99
