### ISSUE TITLE
module : superflexPy, solver : PegasusPython, Error message : fa and fb have the same sign: -0.04886536502251221 vs -0.09954819146324694

### ISSUE THREAD

**Issue by haozhen315** [dalmo1991/superflexPy#3]
Hi there,

I found superflexPy you bulit is very easy to use, however, I found a issue that when I tried to run the gr4j model, this error message showed:
`[ValueError: module : superflexPy, solver : PegasusPython, Error message : fa and fb have the same sign: -0.04886536502251221 vs -0.09954819146324694]()
`
when I run:
`output = model.get_output(solve=True)
`
I set the parameters by:

```
rng = np.random
# Generate the parameters randomly
parameters = rng.rand(4)

# Construct the dictionary for the set_parameters method
parameters_to_set = {
    'model_ps_x1': parameters[0],
    'model_ps_alpha': parameters[1],   
    'model_ps_beta': parameters[2],   
    'model_ps_ni': parameters[3],   
}
```

is this because the parameters of the model are wrong?

many thanks

**Comment by dalmo1991** [comment]
I close the issue due to inactivity
