### ISSUE TITLE
Pip installation issue

### ISSUE THREAD

**Issue by aayushukla** [dalmo1991/superflexPy#8]
While trying to run this command in google colab: !pip install superflexpy

Getting this error:

Collecting superflexpy
  Using cached superflexpy-1.3.1.tar.gz (28 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dalmo1991** [comment]
Version 1.3.2 should have solved the issue. Thanks for pointing that out!
